#data.py is a prototype for data for jobroles and taxanomy

JOB_CORPUS = [
    {
        "id": "data-scientist",
        "title": "Data Scientist",
        "tags": ["python", "machine learning", "statistics", "sql", "data analysis",
                 "pandas", "numpy", "scikit-learn", "tensorflow", "jupyter",
                 "data visualisation", "r", "deep learning", "feature engineering",
                 "regression", "classification", "clustering", "nlp", "data wrangling"],
        "description": "Extracts insights from complex datasets using statistical modelling and ML.",
        "popularity": 0.95,
    },
    {
        "id": "ml-engineer",
        "title": "Machine Learning Engineer",
        "tags": ["python", "machine learning", "tensorflow", "pytorch", "deep learning",
                 "mlops", "docker", "kubernetes", "model deployment", "api development",
                 "numpy", "scikit-learn", "feature engineering", "ci/cd", "aws",
                 "data pipelines", "transformers", "nlp", "cuda"],
        "description": "Bridges research and production — builds, trains, and deploys ML models at scale.",
        "popularity": 0.90,
    },
    {
        "id": "backend-developer",
        "title": "Backend Developer",
        "tags": ["python", "java", "node.js", "sql", "rest api", "api development",
                 "databases", "postgresql", "mongodb", "redis", "docker",
                 "microservices", "authentication", "aws", "system design",
                 "git", "linux", "graphql"],
        "description": "Designs and builds server-side logic, databases, and APIs.",
        "popularity": 0.88,
    },
    {
        "id": "frontend-developer",
        "title": "Frontend Developer",
        "tags": ["javascript", "react", "html", "css", "typescript",
                 "vue.js", "ui/ux", "responsive design", "webpack", "rest api",
                 "git", "testing", "figma", "tailwind css",
                 "accessibility", "next.js", "graphql", "animation"],
        "description": "Crafts interactive, accessible user interfaces.",
        "popularity": 0.87,
    },
    {
        "id": "devops-engineer",
        "title": "DevOps Engineer",
        "tags": ["docker", "kubernetes", "ci/cd", "aws", "linux", "terraform",
                 "ansible", "jenkins", "monitoring", "git", "bash scripting",
                 "infrastructure as code", "networking", "security", "helm",
                 "prometheus", "grafana", "azure", "gcp", "reliability engineering"],
        "description": "Automates infrastructure, deployment pipelines, and monitoring.",
        "popularity": 0.85,
    },
    {
        "id": "cloud-architect",
        "title": "Cloud Architect",
        "tags": ["aws", "azure", "gcp", "cloud computing", "terraform", "kubernetes",
                 "microservices", "system design", "networking", "security",
                 "serverless", "docker", "infrastructure as code",
                 "databases", "reliability engineering", "ci/cd", "monitoring", "linux"],
        "description": "Designs scalable, cost-effective cloud infrastructure.",
        "popularity": 0.82,
    },
    {
        "id": "fullstack-developer",
        "title": "Full Stack Developer",
        "tags": ["javascript", "python", "react", "node.js", "sql", "mongodb",
                 "rest api", "html", "css", "git", "docker", "aws",
                 "typescript", "graphql", "authentication", "testing", "databases",
                 "api development", "responsive design", "postgresql"],
        "description": "Works across the full application stack end-to-end.",
        "popularity": 0.86,
    },
    {
        "id": "data-engineer",
        "title": "Data Engineer",
        "tags": ["python", "sql", "apache spark", "data pipelines", "aws", "kafka",
                 "airflow", "postgresql", "data warehousing", "etl", "hadoop",
                 "bigquery", "dbt", "linux", "docker", "databases",
                 "data wrangling", "mongodb", "snowflake", "bash scripting"],
        "description": "Builds and maintains the data infrastructure that analysts depend on.",
        "popularity": 0.83,
    },
    {
        "id": "cybersecurity-analyst",
        "title": "Cybersecurity Analyst",
        "tags": ["networking", "linux", "security", "python", "ethical hacking",
                 "penetration testing", "firewalls", "cryptography", "siem",
                 "incident response", "bash scripting", "vulnerability assessment",
                 "compliance", "authentication", "threat modelling", "aws"],
        "description": "Defends systems and networks from threats.",
        "popularity": 0.80,
    },
    {
        "id": "ai-engineer",
        "title": "AI Engineer",
        "tags": ["python", "machine learning", "nlp", "transformers", "pytorch",
                 "tensorflow", "deep learning", "llm", "prompt engineering", "api development",
                 "langchain", "vector databases", "rag", "mlops", "model deployment",
                 "data analysis", "scikit-learn", "aws", "docker", "fine-tuning"],
        "description": "Builds intelligent systems using modern AI and LLMs.",
        "popularity": 0.98,
    },
    {
        "id": "mobile-developer",
        "title": "Mobile Developer",
        "tags": ["react native", "flutter", "swift", "kotlin", "javascript",
                 "typescript", "android", "ios", "rest api", "ui/ux",
                 "firebase", "git", "testing", "graphql",
                 "databases", "authentication", "figma"],
        "description": "Builds cross-platform or native mobile applications.",
        "popularity": 0.81,
    },
    {
        "id": "blockchain-developer",
        "title": "Blockchain Developer",
        "tags": ["solidity", "ethereum", "web3", "javascript", "python",
                 "smart contracts", "cryptography", "truffle", "hardhat",
                 "react", "node.js", "security", "git",
                 "rust", "consensus algorithms", "zero knowledge proofs"],
        "description": "Develops decentralised applications and smart contracts.",
        "popularity": 0.72,
    },
]

SKILL_CATEGORIES = {
    "Languages & Core": [
        "Python", "JavaScript", "TypeScript", "Java", "C++", "SQL",
        "Rust", "Go", "Swift", "Kotlin", "R", "Bash Scripting", "Solidity",
    ],
    "Frameworks & Tools": [
        "React", "Node.js", "Docker", "Kubernetes", "TensorFlow", "PyTorch",
        "AWS", "Azure", "GCP", "Git", "Terraform", "Scikit-learn",
        "Pandas", "NumPy", "PostgreSQL", "MongoDB", "Redis", "GraphQL",
        "Next.js", "Vue.js", "Flutter", "Firebase", "Kafka", "Apache Spark",
    ],
    "Domains & Concepts": [
        "Machine Learning", "Deep Learning", "NLP", "Data Analysis", "MLOps",
        "CI/CD", "Microservices", "System Design", "API Development", "Data Pipelines",
        "Cloud Computing", "Security", "Networking", "UI/UX",
        "Data Visualisation", "Databases", "Statistics", "Linux",
        "Transformers", "LLM", "Prompt Engineering", "Feature Engineering",
        "CUDA", "RAG", "Fine-tuning", "LangChain",
    ],
}
